(() => {
  const app=document.getElementById('app'),dialog=document.getElementById('dialog'),cards=window.JokerCards;
  let counts=[...window.JokerDefaultCounts],nature='Água',screen='menu',battle=null,selected=-1,botTimer=null;
  try{const saved=JSON.parse(localStorage.getItem('joker-water-deck'));if(saved&&JokerEngine.valid(saved.counts)){counts=saved.counts;if(['Água','Fogo','Terra','Vento'].includes(saved.nature))nature=saved.nature;}}catch(_){}
  const total=()=>counts.reduce((a,b)=>a+b,0),image=id=>`assets/${cards[id].id}.png`;
  const esc=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
  function save(){if(JokerEngine.valid(counts))try{localStorage.setItem('joker-water-deck',JSON.stringify({counts,nature}));}catch(_){}}
  function cancelBot(){clearTimeout(botTimer);botTimer=null;}
  function menu(){cancelBot();screen='menu';app.innerHTML=`<section class="hero"><div><p class="eyebrow">DECK BUILDER · ÁGUA</p><h1>O chamado<br>das águas.</h1><p>Construa seu deck. Preserve sua vida.<br>Duele com a força dos rios brasileiros.</p><div class="menu-buttons"><button class="primary" data-action="start">INICIAR DUELO →</button><button data-action="builder">CONSTRUIR DECK</button><button data-action="rules">COMO JOGAR</button></div><p class="small">100 HP · 30 cartas · 6 na mão · Escudo persistente</p></div><div class="hero-art" aria-hidden="true"><img src="${image(6)}" alt=""><img src="${image(7)}" alt=""><img src="${image(0)}" alt=""></div></section>`;}
  function builder(){cancelBot();screen='builder';app.innerHTML=`<div class="toolbar"><div><h2>Construa seu deck</h2><p class="${total()===30?'muted':'notice'}">${total()} / 30 cartas · 12 tipos de Água</p></div><button data-action="menu">MENU</button></div><div class="catalog">${cards.map((c,id)=>`<article><img src="${image(id)}" alt="${esc(c.name)}" loading="lazy"><h3>${esc(c.name)}</h3><span class="small">${esc(c.kind)} · ${c.cost} energia</span><p class="effect">${esc(c.text)}</p><div class="copy-controls"><button data-action="count" data-id="${id}" data-delta="-1" aria-label="Remover cópia de ${esc(c.name)}" ${counts[id]<=1?'disabled':''}>−</button><span>${counts[id]} cópias</span><button data-action="count" data-id="${id}" data-delta="1" aria-label="Adicionar cópia de ${esc(c.name)}" ${counts[id]>=6||total()>=30?'disabled':''}>+</button></div></article>`).join('')}</div><div class="footer-controls"><label>Natureza do mago <select id="nature">${['Água','Fogo','Terra','Vento'].map(n=>`<option ${n===nature?'selected':''}>${n}</option>`).join('')}</select></label><button data-action="restore">RESTAURAR DECK</button><button class="primary" data-action="start" ${JokerEngine.valid(counts)?'':'disabled'}>SALVAR E DUELAR →</button></div><p class="small">1 a 6 cópias por tipo. Complete exatamente 30 cartas. Para trocar uma cópia, remova uma antes de adicionar outra.</p>`;}
  function rules(){cancelBot();screen='rules';app.innerHTML=`<div class="toolbar"><h2>Como jogar</h2><button data-action="menu">MENU</button></div><div class="rules"><section><h2 class="gold">Sobreviver melhor é vencer.</h2><p>Você e o Xamã começam com <strong>100 HP</strong>, um deck de <strong>30 cartas</strong> e <strong>6 cartas na mão</strong>. A partida termina quando ambos tiverem usado todas as cartas do monte e da mão. <strong>Vence quem tiver mais HP restante.</strong> HP igual é empate.</p><p>Chegar a 0 HP não encerra o duelo. Você ainda pode usar suas cartas e recuperar vida.</p></section><section><h3>Seu turno, passo a passo</h3><ol><li>Receba <strong>4 energia</strong> mais a reserva do turno anterior. Sua mão é reposta até 6 cartas.</li><li><strong>Clique ou toque em uma carta</strong> para ler os efeitos. Depois toque em <strong>Jogar esta carta</strong>. Cada carta consome a energia indicada.</li><li>Combine ataques, Defesas, curas e maldições. Cartas com borda verde têm energia suficiente.</li><li>Toque em <strong>Encerrar turno</strong>. Você guarda até 2 energia e mantém as cartas não usadas na mão.</li></ol><p>No celular, deslize a mão para ver todas as cartas. O Xamã joga automaticamente.</p></section><section><h3>Escudo, cura e combos</h3><p>Escudo absorve dano antes do HP e permanece entre os turnos. Com <strong>80 HP + 6 Escudo</strong>, receber 10 de dano deixa você com <strong>76 HP + 0 Escudo</strong>.</p><p>Jogar <strong>duas Defesas no mesmo turno cura 2 HP</strong>, uma vez por turno. Cura nunca ultrapassa 100 HP.</p><p>Maldições reduzem o próximo ataque compatível e acumulam. Enlameado espera um ataque físico; Cheia e Arrasto afetam qualquer ataque. Corrente do Solimões remove Escudo antes do dano. Fluxo Restaurador melhora a próxima Defesa.</p></section><section><h3>Construção do deck e Naturezas</h3><p>Use <strong>Construir deck</strong> para distribuir as cópias entre os 12 tipos de Água. Mantenha de 1 a 6 cópias de cada tipo e exatamente 30 cartas no total. O último deck válido é salvo neste navegador.</p><p>Água → Fogo → Terra → Vento → Água. A vantagem dá +25% de dano; a desvantagem dá -25%. As cartas são de Água, mesmo se a Natureza do seu mago for outra.</p><p>O descarte <strong>não é reembaralhado</strong>. Sem cartas para jogar, o jogador é pulado enquanto o outro termina seu deck.</p></section><button class="primary" data-action="start">ENTENDI, VAMOS JOGAR →</button></div>`;}
  function start(){if(!JokerEngine.valid(counts))return;cancelBot();save();battle=new JokerEngine.Battle(counts,nature);screen='battle';selected=-1;renderBattle();}
  function stats(p,i){return `<section class="stat ${battle.turn===i?'active':''}"><h3>${battle.name(i)} · ${p.nature}</h3><div class="numbers"><span class="hp">${p.hp} HP</span><span class="shield">${p.shield} Escudo</span><span class="energy">${p.energy} Energia</span></div><p>Monte ${p.deck.length} · Mão ${p.hand.length} · Usadas ${p.discard.length}/30</p></section>`;}
  function detail(){const p=battle.players[0];if(selected<0||selected>=p.hand.length)return `<aside class="details"><h3>Escolha uma carta</h3><p>Clique ou toque em uma carta da mão para ler os efeitos e jogar.</p><p>Você pode usar várias cartas enquanto tiver energia. Escudo fica acumulado entre os turnos.</p></aside>`;const id=p.hand[selected],c=cards[id],can=battle.turn===0&&battle.canPlay(selected);return `<aside class="details"><img src="${image(id)}" alt="${esc(c.name)}"><h3>${esc(c.name)}</h3><p>${esc(c.kind)} · ${c.cost} energia</p><p>${esc(c.text)}</p><button class="primary" data-action="play" ${can?'':'disabled'}>${battle.turn!==0?'AGUARDE O XAMÃ':can?'JOGAR ESTA CARTA':'ENERGIA INSUFICIENTE'}</button></aside>`;}
  function renderBattle(){if(battle.finished){result();return;}screen='battle';const p=battle.players[0],status=[];if(p.weak_any)status.push(`Próximo ataque: -${p.weak_any}`);if(p.weak_physical)status.push(`Próximo físico: -${p.weak_physical}`);if(p.boost)status.push(`Próxima Defesa: +${p.boost}`);app.innerHTML=`<div class="toolbar"><h2>Duelo · Rodada ${battle.round}</h2><button data-action="leave">MENU</button></div><div class="stats">${battle.players.map(stats).join('')}</div><div class="battle-grid"><div><section class="log"><strong class="gold">${battle.turn===0?'SUA VEZ':'O XAMÃ ESTÁ JOGANDO…'}</strong>${battle.history.slice(-3).map(s=>`<p>${esc(s)}</p>`).join('')}</section><p class="status">${status.join(' · ')||'Defesa → Defesa: +2 HP. Planeje a ordem das cartas.'}</p><div class="hand-title"><h3>SUA MÃO</h3><button class="primary" data-action="end" ${battle.turn!==0?'disabled':''}>ENCERRAR TURNO</button></div><div class="hand">${p.hand.map((id,index)=>`<button class="hand-card ${battle.turn===0&&battle.canPlay(index)?'playable':'unplayable'} ${selected===index?'selected':''}" data-action="select" data-index="${index}" aria-label="Ver ${esc(cards[id].name)}"><img src="${image(id)}" alt="${esc(cards[id].name)}"><span class="cost">${cards[id].cost} energia</span></button>`).join('')||'<p class="muted">Você usou todas as cartas. Encerre o turno para o Xamã terminar.</p>'}</div><p class="small">Clique ou toque para selecionar. No celular, deslize a mão para ver todas as cartas.</p></div>${detail()}</div>`;scheduleBot();}
  function scheduleBot(){if(botTimer||battle.turn!==1||battle.finished||dialog.open)return;botTimer=setTimeout(()=>{botTimer=null;if(screen!=='battle'||dialog.open)return;battle.botStep();renderBattle();},700);}
  function result(){cancelBot();screen='result';const title=battle.winner<0?'EMPATE':battle.winner===0?'VOCÊ VENCEU!':'O XAMÃ VENCEU';app.innerHTML=`<section class="result"><p class="eyebrow">OS DOIS DECKS FORAM ESGOTADOS</p><h1>${title}</h1><p class="score">Você: ${battle.players[0].hp} HP &nbsp; × &nbsp; Xamã: ${battle.players[1].hp} HP</p><p class="muted">Quem preservou mais vida levou o duelo.</p><div class="actions"><button class="primary" data-action="start">NOVO DUELO</button><button data-action="builder">AJUSTAR MEU DECK</button><button data-action="menu">MENU</button></div></section>`;}
  function leave(){cancelBot();dialog.innerHTML='<h3>Voltar ao menu?</h3><p>O duelo atual será encerrado.</p><div class="actions"><button class="primary" data-action="continue">CONTINUAR DUELO</button><button data-action="confirm-leave">VOLTAR AO MENU</button></div>';dialog.showModal();}
  function action(event){const b=event.target.closest('button[data-action]');if(!b||b.disabled)return;const a=b.dataset.action;if(a==='menu')menu();else if(a==='builder')builder();else if(a==='rules')rules();else if(a==='start')start();else if(a==='count'){const id=Number(b.dataset.id),delta=Number(b.dataset.delta);counts[id]=Math.max(1,Math.min(6,counts[id]+delta));save();const y=scrollY;builder();scrollTo(0,y);}else if(a==='restore'){counts=[...JokerDefaultCounts];nature='Água';save();builder();}else if(a==='select'){const hand=app.querySelector('.hand'),x=hand.scrollLeft,y=scrollY;selected=Number(b.dataset.index);renderBattle();app.querySelector('.hand').scrollLeft=x;scrollTo(0,y);if(innerWidth<701)app.querySelector('.details').scrollIntoView({behavior:'smooth',block:'nearest'});}else if(a==='play'){if(battle.turn===0&&battle.play(selected)){selected=-1;renderBattle();if(innerWidth<701&&screen==='battle')app.querySelector('.hand-title').scrollIntoView({behavior:'smooth',block:'nearest'});}}else if(a==='end'){if(battle.turn===0){battle.end();selected=-1;renderBattle();}}else if(a==='leave')leave();else if(a==='continue'){dialog.close();scheduleBot();}else if(a==='confirm-leave'){dialog.close();menu();}}
  document.addEventListener('click',action);
  app.addEventListener('change',e=>{if(e.target.id==='nature'){nature=e.target.value;save();}});
  document.getElementById('brand').addEventListener('click',e=>{e.preventDefault();if(screen==='battle')leave();else menu();});
  document.getElementById('fullscreen').addEventListener('click',async()=>{try{if(document.fullscreenElement)await document.exitFullscreen();else await document.documentElement.requestFullscreen();}catch(_){}});
  dialog.addEventListener('cancel',()=>setTimeout(scheduleBot,0));
  document.addEventListener('keydown',e=>{if(e.key==='Escape'&&!dialog.open){if(screen==='battle')leave();else menu();}});
  if('serviceWorker' in navigator&&/^https?:$/.test(location.protocol))navigator.serviceWorker.register('sw.js').catch(()=>{});
  window.JokerUI={menu,builder,rules,start,get battle(){return battle;},get screen(){return screen;},renderBattle};
  menu();
})();
